language: go

go:
  - 1.9

sudo: false

before_install:
  - export GOPATH=$HOME/gopath/src/github.com/owenliang/bigpipe
  - export PATH=$PATH:$HOME/gopath/src/github.com/owenliang/bigpipe/bin/
  - mkdir -p bin && curl https://glide.sh/get | sh

script:
  - sh build.sh